/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import javax.swing.JTable;
import controller.*;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Nathaleon
 */
public class MainView extends javax.swing.JFrame {
    DataProdukController dc;
    DataOrderController dO;
    public MainView() {
        initComponents();
        dc = new DataProdukController(this );
        dc.isiTabel();
        dO = new DataOrderController(this );
        dO.isiTabel();
       
        enableupdate();
    }
    

    /**
     * Creates new form MainView
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        t_CategoryID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        t_UnitPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t_UnitsInStock = new javax.swing.JTextField();
        B_Tambah = new javax.swing.JButton();
        B_Delete = new javax.swing.JButton();
        B_Update = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t_QuantityPerUnit = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_data = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        t_ProductName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t_SupplierID = new javax.swing.JTextField();
        t_ProductID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        B_Clear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Order = new javax.swing.JTable();
        O_ProductID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        O_Quantity = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        O_UnitPrice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        O_Discount = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        B_SelesaikanOrder = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        O_OrderID = new javax.swing.JTextField();
        BO_Tambah = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        t_CategoryID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_CategoryIDActionPerformed(evt);
            }
        });

        jLabel5.setText("Harga");

        t_UnitPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_UnitPriceActionPerformed(evt);
            }
        });

        jLabel6.setText("stok");

        t_UnitsInStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_UnitsInStockActionPerformed(evt);
            }
        });

        B_Tambah.setText("Tambah");
        B_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_TambahActionPerformed(evt);
            }
        });

        B_Delete.setText("Delete");
        B_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_DeleteActionPerformed(evt);
            }
        });

        B_Update.setText("Update");
        B_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_UpdateActionPerformed(evt);
            }
        });

        jLabel8.setText("ProductID");

        jLabel4.setText("Kuantitas Per Unit");

        t_QuantityPerUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_QuantityPerUnitActionPerformed(evt);
            }
        });

        tbl_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Produk", "Supplier", "Kategori", "Kuantitas Per Unit", "Harga", "Stok", "UnitsOnOrder"
            }
        ));
        tbl_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_data);

        jLabel1.setText("Nama Produk");

        t_ProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_ProductNameActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Supplier");

        t_SupplierID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_SupplierIDActionPerformed(evt);
            }
        });

        jLabel3.setText("ID Kategori");

        B_Clear.setText("Clear");
        B_Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_ClearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(t_UnitPrice, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(t_QuantityPerUnit, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(t_CategoryID, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(t_SupplierID, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(t_ProductName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(t_UnitsInStock, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(t_ProductID))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(B_Tambah)
                                    .addComponent(B_Update))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(B_Delete)
                                    .addComponent(B_Clear))))
                        .addGap(6, 6, 6)))
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_ProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_SupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_CategoryID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_QuantityPerUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_UnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_UnitsInStock, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Tambah)
                    .addComponent(B_Delete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Update)
                    .addComponent(B_Clear))
                .addGap(23, 23, 23))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Produk", jPanel1);

        tbl_Order.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "OrderID", "ProductID", "Harga", "Quantity", "Discount"
            }
        ));
        tbl_Order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_OrderMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_Order);

        O_ProductID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O_ProductIDActionPerformed(evt);
            }
        });

        jLabel9.setText("ProductID");

        O_Quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O_QuantityActionPerformed(evt);
            }
        });

        jLabel10.setText("Jumlah");

        jLabel11.setText("Harga");

        O_UnitPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O_UnitPriceActionPerformed(evt);
            }
        });

        jLabel12.setText("Diskon");

        O_Discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O_DiscountActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(179, 198, 240));

        B_SelesaikanOrder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        B_SelesaikanOrder.setText("Selesaikan Order");
        B_SelesaikanOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_SelesaikanOrderActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("OrderID");

        O_OrderID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(B_SelesaikanOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(O_OrderID))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(O_OrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(B_SelesaikanOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BO_Tambah.setText("Tambah");
        BO_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BO_TambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(O_ProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(O_Discount, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(11, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(O_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(O_UnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BO_Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(O_ProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(O_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(O_UnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BO_Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(O_Discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Orders", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void BO_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BO_TambahActionPerformed
        try{
        dO.insert();
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Data masih kosong");
        }
        dO.isiTabel();
        dc.isiTabel();
    }//GEN-LAST:event_BO_TambahActionPerformed

    private void B_SelesaikanOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_SelesaikanOrderActionPerformed
       try{
        dO.delete();
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Data masih ada kosong");
        }
        dO.isiTabel();
        dc.isiTabel();
    }//GEN-LAST:event_B_SelesaikanOrderActionPerformed

    private void O_DiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O_DiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_O_DiscountActionPerformed

    private void O_UnitPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O_UnitPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_O_UnitPriceActionPerformed

    private void O_QuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O_QuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_O_QuantityActionPerformed

    private void O_ProductIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O_ProductIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_O_ProductIDActionPerformed

    private void tbl_OrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_OrderMouseClicked
        // TODO add your handling code here:
        int baris = tbl_Order.getSelectedRow();
        O_OrderID.setText(tbl_Order.getValueAt(baris, 0).toString());
        O_ProductID.setText(tbl_Order.getValueAt(baris, 1).toString());
        O_UnitPrice.setText(tbl_Order.getValueAt(baris, 2).toString());
        O_Quantity.setText(tbl_Order.getValueAt(baris, 3).toString());
        O_Discount.setText(tbl_Order.getValueAt(baris, 4).toString());
    }//GEN-LAST:event_tbl_OrderMouseClicked

    private void B_ClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_ClearMouseClicked

        enableupdate();
        t_ProductID.setText("");
        t_ProductName.setText("");
        t_SupplierID.setText("");
        t_CategoryID.setText("");
        t_QuantityPerUnit.setText("");
        t_UnitsInStock.setText("");
        t_UnitPrice.setText("");
    }//GEN-LAST:event_B_ClearMouseClicked

    private void t_SupplierIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_SupplierIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_SupplierIDActionPerformed

    private void t_ProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_ProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_ProductNameActionPerformed

    private void tbl_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dataMouseClicked
        int baris = tbl_data.getSelectedRow();
        t_ProductID.setText(tbl_data.getValueAt(baris, 0).toString());
        t_ProductName.setText(tbl_data.getValueAt(baris, 1).toString());
        t_SupplierID.setText(tbl_data.getValueAt(baris, 2).toString());
        t_CategoryID.setText(tbl_data.getValueAt(baris, 3).toString());
        t_QuantityPerUnit.setText(tbl_data.getValueAt(baris, 4).toString());
        t_UnitPrice.setText(tbl_data.getValueAt(baris, 5).toString());
        t_UnitsInStock.setText(tbl_data.getValueAt(baris, 6).toString());
        disableupdate();
    }//GEN-LAST:event_tbl_dataMouseClicked

    private void t_QuantityPerUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_QuantityPerUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_QuantityPerUnitActionPerformed

    private void B_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_UpdateActionPerformed
        // TODO add your handling code here:
        try{
        dc.update();
          }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Data masih ada yamg kosong");
        }
        dc.isiTabel();
    }//GEN-LAST:event_B_UpdateActionPerformed

    private void B_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_DeleteActionPerformed
        // TODO add your handling code here:
        try{
        dc.delete();
          }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Product ID kosong");
        }
        dc.isiTabel();
    }//GEN-LAST:event_B_DeleteActionPerformed

    private void B_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_TambahActionPerformed
        // TODO add your handling code here:
        try{
        dc.insert();
          }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Data masih kosong");
        }
        dc.isiTabel();
    }//GEN-LAST:event_B_TambahActionPerformed

    private void t_UnitsInStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_UnitsInStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_UnitsInStockActionPerformed

    private void t_UnitPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_UnitPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_UnitPriceActionPerformed

    private void t_CategoryIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_CategoryIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_CategoryIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }
    private void disableupdate(){
    t_ProductID.setEnabled(true);
    B_Tambah.setEnabled(false);
    B_Update.setEnabled(true);
    B_Delete.setEnabled(true);
    
}
    private void enableupdate(){
    t_ProductID.setEnabled(false); 
    B_Tambah.setEnabled(true);
    B_Update.setEnabled(false);
    B_Delete.setEnabled(false);
    
}
     public JTable gettbl_data() {
        return tbl_data;
    }

    public void settbl_data(JTable tbl_data) {
        this.tbl_data = tbl_data;
    }
    
     public JTable gettbl_Order() {
        return tbl_Order;
    }

    public void settbl_Order(JTable tbl_Order) {
        this.tbl_Order = tbl_Order;
    }

    public JTextField gett_QuantityPerUnit() {
        return t_QuantityPerUnit;
    }

    public void sett_QuantityPerUnit(JTextField t_QuantityPerUnit) {
        this.t_QuantityPerUnit = t_QuantityPerUnit;
    }

    public JTextField gett_SupplierID() {
        return t_SupplierID;
    }

    public void sett_SupplierID(JTextField t_SupplierID) {
        this.t_SupplierID = t_SupplierID;
    }

    public JTextField gett_ProductName() {
        return t_ProductName;
    }

    public void sett_ProductName(JTextField t_ProductName) {
        this.t_ProductName = t_ProductName;
    }

    public JTextField gett_CategoryID() {
        return t_CategoryID;
    }

    public void sett_CategoryID(JTextField t_categoryID) {
        this.t_CategoryID = t_categoryID;
    }
    public JTextField gett_UnitPrice() {
        return t_UnitPrice;
    }

    public void sett_UnitPrice(JTextField t_UnitPrice) {
        this.t_UnitPrice = t_UnitPrice;
    }
    
    public JTextField gett_UnitsInStock() {
        return t_UnitsInStock;
    }

    public void sett_UnitsInStock(JTextField t_UnitsInStock) {
        this.t_UnitsInStock = t_UnitsInStock;
    }
    
    public JTextField gett_ProductID() {
        return t_ProductID;
    }

    public void sett_ProductID(JTextField t_ProductID) {
        this.t_ProductID = t_ProductID;
    }
    

    //page 3 cuyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
    
    public JTextField getO_ProductID() {
        return O_ProductID;
    }

    public void setO_ProductID(JTextField O_ProductID) {
        this.O_ProductID = O_ProductID;
    }
    
    public JTextField getO_Quantity() {
        return O_Quantity;
    }
    public void setO_Quantity(JTextField O_Quantity) {
        this.O_Quantity = O_Quantity;
    }
    
    public JTextField getO_UnitPrice() {
        return O_UnitPrice;
    }
    public void setO_UnitPrice(JTextField O_UnitPrice) {
        this.O_UnitPrice = O_UnitPrice;
    }
    
    public JTextField getO_Discount() {
        return O_Discount;
    }
    public void setO_Discount(JTextField O_Discount) {
        this.O_Discount = O_Discount;
    }
    
    public JTextField getO_OrderID() {
        return O_OrderID;
    }

    public void setO_OrderID(JTextField O_OrderID) {
        this.O_OrderID = O_OrderID;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BO_Tambah;
    private javax.swing.JButton B_Clear;
    private javax.swing.JButton B_Delete;
    private javax.swing.JButton B_SelesaikanOrder;
    private javax.swing.JButton B_Tambah;
    private javax.swing.JButton B_Update;
    private javax.swing.JTextField O_Discount;
    private javax.swing.JTextField O_OrderID;
    private javax.swing.JTextField O_ProductID;
    private javax.swing.JTextField O_Quantity;
    private javax.swing.JTextField O_UnitPrice;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField t_CategoryID;
    private javax.swing.JTextField t_ProductID;
    private javax.swing.JTextField t_ProductName;
    private javax.swing.JTextField t_QuantityPerUnit;
    private javax.swing.JTextField t_SupplierID;
    private javax.swing.JTextField t_UnitPrice;
    private javax.swing.JTextField t_UnitsInStock;
    private javax.swing.JTable tbl_Order;
    private javax.swing.JTable tbl_data;
    // End of variables declaration//GEN-END:variables
}
